### ISSUE TITLE
lldb-mi: Need documentation on how to set it up

### ISSUE THREAD

**Issue by MarkZ3** [MarkZ3/Eclipse-CDT-WIP#9]
How does one use lldb-mi in CDT?

**Comment by MarkZ3** [comment]
Test

**Comment by kwalcock** [comment]
There is nothing called "CDT update site", not even if "--All Available Sites--" is selected.  There is no "C/C++ LLDB Debugger Integration" listed.  Using "Eclipse IDE for C/C++ Developers" Mars.2 Release on Mac.

**Comment by MarkZ3** [comment]
Hi! This feature is not released yet. The text in this issue is also a work in progress. This should be available in the CDT 9.1 release September 28th.

**Comment by MarkZ3** [comment]
Added the instructions here:
https://wiki.eclipse.org/CDT/User/FAQ#How_do_I_get_the_LLDB_debugger.3F

**Comment by johanneslotz** [comment]
It seems that the command line arguments entered in the "Arguments" tab are ignored. Is this something to be added to the restrictions? Or am I missing something?

**Comment by MarkZ3** [comment]
Hi! Thank you for trying it out! You are right, I just tried it and the
Arguments do not work. I'll look into it. BTW, since the LLDB plug-ins were
merged into the CDT repo, I think I might retire this Github. So
bugs/issues are being moved to https://bugs.eclipse.org/bugs/

I created one for this particular issue
https://bugs.eclipse.org/bugs/show_bug.cgi?id=508610

You might want to CC yourself to that bug.

Thanks a lot for reporting this! I think it should be a quick fix.

**Comment by ajayhr** [comment]
hi all,

i am using hexagon SDK 3.0. when i try to debug using debug configuration using hexagon-lldb it is showing

standard LLDb process launcher
There was a error launching
org.eclipse.core.runtime.CoreException: Error while launching command hexagon-lldb --interpreter mi2 --nx

can anybody solve this

**Comment by MarkZ3** [comment]
Hi ajayhr! Can you report a new bug here: https://bugs.eclipse.org/bugs/
Thanks!
